theme = "onedark"

[editor]
shell = ["sh", "-c"]
true-color = true
rulers = [120]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
# j = { k = "normal_mode" }
"C-/" = "toggle_comments"

[keys.normal]
g = { a = "code_action" }
C-s = ":write"
"C-/" = "toggle_comments"

[keys.select]
"C-/" = "toggle_comments"

[keys.normal.";"]
q = ":quit"
w = ":write"
