[helpers]

[settings]
default_target_type = "automatic"

[bash.files]
"bash/bashrc" = "~/.bashrc"
"bash/bash_profile" = "~/.bash_profile"

[cargo.files]
"cargo/config.toml" = "~/.cargo/config/config.toml"

[git.files]
# local variables: git_name, git_email
"git/gitconfig" = "~/.gitconfig"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"
