[helpers]

[settings]
default_target_type = "automatic"

[cargo.files]
"cargo/config.toml" = "~/.cargo/config/config.toml"

[git.files]
"git/gitconfig" = "~/.gitconfig"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"
