[helix.files]
helix = "~/AppData/Roaming/helix"

[pwsh.files]
"pwsh/profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

[sublime.files]
sublime = "~/AppData/Roaming/Sublime Text/Packages/User"